Repository spon-us/SponUs-iOS-Sprint2, pull requests merged in 2024-07, with the labels that each got.

#49 [#48] 홈뷰 / 프로필 북마크 api연동(상태관리 실패 ,,)
  Spon-Us/Home/HomeView.swift
  Spon-Us/Home/HomeViewModel.swift
  Spon-Us/Network/Models/Bookmark.swift
  Spon-Us/Network/Models/Organization.swift
  Spon-Us/Network/SponusAPI.swift
  Spon-Us/Profile/Club/ClubProfileView.swift
  Spon-Us/Profile/Club/ClubProfileViewModel.swift
  Spon-Us/Profile/Company/CompanyProfileView.swift
  Spon-Us/Profile/Company/CompanyProfileViewModel.swift
Labels: feat 💚

#50 [#48] 홈뷰 / 프로필 북마크 api연동 완료
  Spon-Us/Home/HomeView.swift
  Spon-Us/Home/HomeViewModel.swift
  Spon-Us/Network/Models/Organization.swift
Labels: feat 💚

#46 [feat] 북마크 토글 API 연동
  Spon-Us/Bookmark/BookmarkView.swift
  Spon-Us/Bookmark/BookmarkViewModel.swift
  Spon-Us/Network/Models/Bookmark.swift
  Spon-Us/Network/SponusAPI.swift
Labels: feat 💚

#52 [chore] 북마크 토글 API 수정
  Spon-Us/Bookmark/BookmarkView.swift
  Spon-Us/Bookmark/BookmarkViewModel.swift
  Spon-Us/Network/Models/Bookmark.swift
  Spon-Us/Network/SponusAPI.swift
Labels: chore 🧹

#57 [#56] 서치뷰 이전탭 버튼 / 탭바 숨기기
  Spon-Us/ContentView.swift
  Spon-Us/Search/SearchView.swift
Labels: feat 💚

#58 미사용 캡쳐값 제거
  Spon-Us/MyPage/MyPageViewHelper.swift
  Spon-Us/Network/SponusAPI.swift
  Spon-Us/OnBoarding/View/SignUpIdView.swift
  Spon-Us/OnBoarding/View/SignUpPWView.swift
  Spon-Us/OnBoarding/ViewModel/LoginViewModel.swift
  Spon-Us/OnBoarding/ViewModel/SignUpViewModel.swift
Labels: feat 💚

#61 [#60] org / company / club 프로필 API 필드 변동 대응
  Spon-Us/Home/HomeViewModel.swift
  Spon-Us/Network/Models/Club.swift
  Spon-Us/Network/Models/Company.swift
  Spon-Us/Network/Models/Organization.swift
  Spon-Us/Profile/Club/ClubProfileView.swift
  Spon-Us/Profile/Club/ClubProfileViewModel.swift
  Spon-Us/Profile/Company/CompanyProfileView.swift
  Spon-Us/Profile/Company/CompanyProfileViewModel.swift
Labels: chore 🧹

#63 [#62] 홈뷰/기업, 동아리 프로필뷰 AsyncImage로 교체
  Spon-Us/Home/HomeView.swift
  Spon-Us/Profile/Club/ClubProfileView.swift
  Spon-Us/Profile/Company/CompanyProfileView.swift
Labels: feat 💚

#66 [#65] 탭뷰 onchange -> didset으로 버그 수정
  Spon-Us/ContentView.swift
Labels: fix 🔨

#69 [#68] iOS 17.4 toolbar hidden 버그 대응 / OrganizationLinks 필드 추가 대응
  Spon-Us.xcodeproj/project.pbxproj
  Spon-Us/Home/HomeViewModel.swift
  Spon-Us/Network/Models/Club.swift
  Spon-Us/Profile/Club/ClubProfileView.swift
  Spon-Us/Profile/Club/ClubProfileViewModel.swift
  Spon-Us/Search/SearchView.swift
Labels: fix 🔨

#73 [chore] 검색 텍스트필드 & 리스트 데이터 삭제
  Spon-Us/Search/SearchView.swift
Labels: chore 🧹
