Repository spon-us/SponUs-iOS-Sprint2, pull requests merged in 2024-09, with the labels that each got.

#88 [#87] 홈 기업/동아리 프로필 제안 구현
  Spon-Us.xcodeproj/project.pbxproj
  Spon-Us/EnumManager.swift
  Spon-Us/Home/HomeView.swift
  Spon-Us/Home/HomeViewModel.swift
  Spon-Us/Network/Models/Organization.swift
  Spon-Us/Network/Models/Propose.swift
  Spon-Us/Network/SponusAPI.swift
  Spon-Us/Profile/Club/ClubProfileView.swift
  Spon-Us/Profile/Club/ClubProfileViewModel.swift
  Spon-Us/Profile/Company/CompanyProfileView.swift
  Spon-Us/Profile/Company/CompanyProfileViewModel.swift
Labels: feat 💚

#90 [#87] 홈 무한스크롤 Pagination 구현
  Spon-Us/Bookmark/BookmarkView.swift
  Spon-Us/Home/HomeView.swift
  Spon-Us/Home/HomeViewModel.swift
  Spon-Us/Search/SearchView.swift
Labels: feat 💚

#91 [#87] Pagination 테스트 버튼 제거
  Spon-Us/Home/HomeView.swift
  Spon-Us/Home/HomeViewModel.swift
Labels: feat 💚

#92 [#87] pagesize 수정
  Spon-Us/Home/HomeViewModel.swift
Labels: feat 💚

#93 [#87] 중복 제안 방지 로직 추가
  Spon-Us/Profile/Club/ClubProfileView.swift
  Spon-Us/Profile/Club/ClubProfileViewModel.swift
  Spon-Us/Profile/Company/CompanyProfileView.swift
  Spon-Us/Profile/Company/CompanyProfileViewModel.swift
Labels: feat 💚

#94 [#87] 홈뷰 포트폴리오 작성 카드 조건 추가 / 프로필이미지 및 단체명 추가
  Spon-Us/Home/HomeView.swift
  Spon-Us/Home/HomeViewModel.swift
  Spon-Us/MyPage/Network/MyPageModel.swift
Labels: feat 💚

#95 [feat] 이전 협업 관리 구현
  Spon-Us.xcodeproj/project.pbxproj
  Spon-Us/MyPage/Network/PreviousProposeViewModel.swift
  Spon-Us/MyPage/PreviousProposeView.swift
  Spon-Us/Network/Models/PreviousPropose.swift
  Spon-Us/Network/SponusAPI.swift
Labels: feat 💚

#96 [chore] 이전 협업 제안별 상태값 다르게 처리
  Spon-Us/MyPage/PreviousProposeView.swift
Labels: chore 🧹

#98 [#97] 홈 포트폴리오 작성 카드 기업 비활성화
  Spon-Us/Home/HomeView.swift
Labels: fix 🔨
