Repository spon-us/SponUs-iOS-Sprint2, pull requests merged in 2024-06, with the labels that each got.

#24 [feat] 검색 UI 구현
  SearchView.swift
  Spon-Us.xcodeproj/project.pbxproj
  Spon-Us/Assets.xcassets/AccentColor.colorset/Contents.json
  Spon-Us/Assets.xcassets/icDelete.imageset/Contents.json
  Spon-Us/Assets.xcassets/icDelete.imageset/icDelete@1x.png
  Spon-Us/Assets.xcassets/icDelete.imageset/icDelete@2x.png
  Spon-Us/Assets.xcassets/icDelete.imageset/icDelete@3x.png
  Spon-Us/ContentView.swift
  Spon-Us/Search/SearchView.swift
Labels: feat 💚

#28 [fix] SearchView 파일 위치 변경
  SearchView.swift
  Spon-Us.xcodeproj/project.pbxproj
Labels: fix 🔨

#30 [Feat/#29] 로그인 로직 + UI 일부 구현
  Spon-Us.xcodeproj/project.pbxproj
  Spon-Us.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Spon-Us/Assets.xcassets/Image 4.imageset/Contents.json
  Spon-Us/Assets.xcassets/Image 4.imageset/icRight.png
  Spon-Us/Assets.xcassets/Tick Square 2.imageset/Contents.json
  Spon-Us/Assets.xcassets/Tick Square 2.imageset/Tick Square.png
  Spon-Us/Assets.xcassets/Tick Square 2.imageset/Tick Square@2x.png
  Spon-Us/Assets.xcassets/Tick Square 2.imageset/Tick Square@3x.png
  Spon-Us/Assets.xcassets/Tick Square 3.imageset/Contents.json
  Spon-Us/Assets.xcassets/Tick Square 3.imageset/Tick Square.png
  Spon-Us/Assets.xcassets/Tick Square 3.imageset/Tick Square@2x.png
  Spon-Us/Assets.xcassets/Tick Square 3.imageset/Tick Square@3x.png
  Spon-Us/Assets.xcassets/icRight1.imageset/Contents.json
  Spon-Us/Assets.xcassets/icRight1.imageset/icRight.png
  Spon-Us/Assets.xcassets/icRight1.imageset/icRight@2x.png
  Spon-Us/Assets.xcassets/icRight1.imageset/icRight@3x.png
  Spon-Us/Assets.xcassets/icRight2.imageset/Contents.json
  Spon-Us/Assets.xcassets/icRight2.imageset/icRight.png
  Spon-Us/Assets.xcassets/icRight2.imageset/icRight@2x.png
  Spon-Us/Assets.xcassets/icRight2.imageset/icRight@3x.png
  Spon-Us/Assets.xcassets/logo_main.imageset/Contents.json
  Spon-Us/Assets.xcassets/logo_main.imageset/logo_main.png
  Spon-Us/Assets.xcassets/logo_main.imageset/logo_main@2x.png
  Spon-Us/Assets.xcassets/logo_main.imageset/logo_main@3x.png
  Spon-Us/Assets.xcassets/logo_main_black.imageset/Contents.json
  Spon-Us/Assets.xcassets/logo_main_black.imageset/logo_main.png
  Spon-Us/Assets.xcassets/logo_main_black.imageset/logo_main@2x.png
  Spon-Us/Assets.xcassets/logo_main_black.imageset/logo_main@3x.png
  Spon-Us/Assets.xcassets/onBoarding.imageset/Contents.json
  Spon-Us/Assets.xcassets/onBoarding.imageset/Rectangle 1277.png
  Spon-Us/Assets.xcassets/onBoarding.imageset/Rectangle 1277@2x.png
  Spon-Us/Assets.xcassets/onBoarding.imageset/Rectangle 1277@3x.png
  Spon-Us/Assets.xcassets/policy1.imageset/Contents.json
  Spon-Us/Assets.xcassets/policy1.imageset/processing_policy.png
  Spon-Us/Assets.xcassets/policy1.imageset/processing_policy@2x.png
  Spon-Us/Assets.xcassets/policy1.imageset/processing_policy@3x.png
  Spon-Us/Assets.xcassets/policy2.imageset/Contents.json
  Spon-Us/Assets.xcassets/policy2.imageset/Frame 37338.png
  Spon-Us/Assets.xcassets/policy2.imageset/Frame 37338@2x.png
  Spon-Us/Assets.xcassets/policy2.imageset/Frame 37338@3x.png
  Spon-Us/Assets.xcassets/policy3.imageset/Contents.json
  Spon-Us/Assets.xcassets/policy3.imageset/Frame 37336.png
  Spon-Us/Assets.xcassets/policy3.imageset/Frame 37336@2x.png
  Spon-Us/Assets.xcassets/policy3.imageset/Frame 37336@3x.png
  Spon-Us/Assets.xcassets/policy4.imageset/Contents.json
  Spon-Us/Assets.xcassets/policy4.imageset/Frame 37336.png
  Spon-Us/Assets.xcassets/policy4.imageset/Frame 37336@2x.png
  Spon-Us/Assets.xcassets/policy4.imageset/Frame 37336@3x.png
  Spon-Us/Auth/AuthPlugin.swift
  Spon-Us/Auth/TokenManager.swift
  Spon-Us/OnBoarding/AgreeView.swift
  Spon-Us/OnBoarding/DetailAgreeView.swift
  Spon-Us/OnBoarding/LoginView.swift
  Spon-Us/OnBoarding/LoginViewModel.swift
  Spon-Us/OnBoarding/OnBoardingView.swift
  Spon-Us/Spon_UsApp.swift
Labels: feat 💚

#35 [#31] ScrollToTop 버튼 버그 수정
  Spon-Us/Home/HomeView.swift
  Spon-Us/Network/SponusAPI.swift
Labels: feat 💚

#37 [#31] Organization 모델 업데이트
  Spon-Us/ContentView.swift
  Spon-Us/Home/HomeView.swift
  Spon-Us/Home/HomeViewModel.swift
  Spon-Us/Network/Models/Club.swift
  Spon-Us/Network/Models/Company.swift
  Spon-Us/Network/Models/Organization.swift
  Spon-Us/Network/SponusAPI.swift
Labels: feat 💚

#38 [#31] ScrollToTop 버그 수정 / Company Profile 연동중
  Spon-Us/Bookmark/BookmarkView.swift
  Spon-Us/Home/HomeView.swift
  Spon-Us/Home/HomeViewModel.swift
  Spon-Us/Network/Models/Company.swift
  Spon-Us/Profile/Company/CompanyProfileView.swift
  Spon-Us/Profile/Company/CompanyProfileViewModel.swift
Labels: feat 💚

#40 [#31] ScrollToTop 찐찐막 / 홈뷰, 뷰모델 코드 정리
  Spon-Us/Home/HomeView.swift
  Spon-Us/Home/HomeViewModel.swift
  Spon-Us/Profile/Company/CompanyProfileViewModel.swift
Labels: fix 🔨, refactor 🔃

#41 [#31] ScrollToTop 최종
  Spon-Us/Home/HomeView.swift
Labels: fix 🔨

#42 [#31] ScrollToTop 찐찐막
  Spon-Us/Home/HomeView.swift
  Spon-Us/Home/HomeViewModel.swift
Labels: fix 🔨

#43 [feat] SearchView API 연동
  Spon-Us.xcodeproj/project.pbxproj
  Spon-Us/Assets.xcassets/icRight3.imageset/Contents.json
  Spon-Us/Assets.xcassets/icRight3.imageset/icRight3@1x.png
  Spon-Us/Assets.xcassets/icRight3.imageset/icRight3@2x.png
  Spon-Us/Assets.xcassets/icRight3.imageset/icRight3@3x.png
  Spon-Us/Assets.xcassets/musinsa.imageset/Contents.json
  Spon-Us/Assets.xcassets/musinsa.imageset/musinsa_1x.png
  Spon-Us/Assets.xcassets/musinsa.imageset/musinsa_2x.png
  Spon-Us/Assets.xcassets/musinsa.imageset/musinsa_3x.png
  Spon-Us/Assets.xcassets/sponus.imageset/Contents.json
  Spon-Us/Assets.xcassets/sponus.imageset/sponus.svg
  Spon-Us/Bookmark/BookmarkView.swift
  Spon-Us/Bookmark/BookmarkViewModel.swift
  Spon-Us/Extention/HideKeyboardExtension.swift
  Spon-Us/Network/Models/Bookmark.swift
  Spon-Us/Network/Models/Keyword.swift
  Spon-Us/Network/Models/Search.swift
  Spon-Us/Network/SponusAPI.swift
  Spon-Us/Search/SearchView.swift
  Spon-Us/Search/SearchViewModel.swift
Labels: feat 💚
